### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data2/gpxu/popular_debias/pid/data/ml100k/train_coo_record.npz'

### ISSUE THREAD

**Issue by lizhenstat** [XMUDM/NeutralizingBias#2]
Hi, thanks for your great work and sharing of the code!

However, when I running the code, 
the following [directory](https://github.com/XMUDM/NeutralizingBias/blob/main/iid/app.py#L10) is not found.

Thanks for your help!

**Comment by lizhenstat** [comment]
sorry for the stupid question, I find this is the path for the "local pid directory".

**Comment by Stellakats** [comment]
hi @lizhenstat !
Have you been able to reproduce the code?

**Comment by lizhenstat** [comment]
@Stellakats Hi, I just change the code contains the directory "/data2/gpxu/popular_debias/pid/" to the local path, and run app.py, it works.
